[project]
name = "25-isco4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "langchain-community>=0.3.0",
    "langchain-google-genai>=2.1.0",
    "faiss-cpu>=1.9.0",
    "pypdf>=5.0.0",
    "openpyxl>=3.1.0",
    "pandas>=2.2.0",
    "python-dotenv>=1.0.0",
    "ragas>=0.2.0",
    "jsonref>=1.1.0",
    "matplotlib>=3.9.0",
    "jupyterlab>=4.5.2",
]
